# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/joelm/Library/CloudStorage/OneDrive-OregonStateUniversity/Projects/C++/logic-gates-playground

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/joelm/Library/CloudStorage/OneDrive-OregonStateUniversity/Projects/C++/logic-gates-playground

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joelm/Library/CloudStorage/OneDrive-OregonStateUniversity/Projects/C++/logic-gates-playground/CMakeFiles /Users/joelm/Library/CloudStorage/OneDrive-OregonStateUniversity/Projects/C++/logic-gates-playground//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/joelm/Library/CloudStorage/OneDrive-OregonStateUniversity/Projects/C++/logic-gates-playground/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named logic-gates-playground

# Build rule for target.
logic-gates-playground: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logic-gates-playground
.PHONY : logic-gates-playground

# fast build rule for target.
logic-gates-playground/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/build
.PHONY : logic-gates-playground/fast

src/app/Application.o: src/app/Application.cpp.o
.PHONY : src/app/Application.o

# target to build an object file
src/app/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/Application.cpp.o
.PHONY : src/app/Application.cpp.o

src/app/Application.i: src/app/Application.cpp.i
.PHONY : src/app/Application.i

# target to preprocess a source file
src/app/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/Application.cpp.i
.PHONY : src/app/Application.cpp.i

src/app/Application.s: src/app/Application.cpp.s
.PHONY : src/app/Application.s

# target to generate assembly for a file
src/app/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/Application.cpp.s
.PHONY : src/app/Application.cpp.s

src/app/Config.o: src/app/Config.cpp.o
.PHONY : src/app/Config.o

# target to build an object file
src/app/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/Config.cpp.o
.PHONY : src/app/Config.cpp.o

src/app/Config.i: src/app/Config.cpp.i
.PHONY : src/app/Config.i

# target to preprocess a source file
src/app/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/Config.cpp.i
.PHONY : src/app/Config.cpp.i

src/app/Config.s: src/app/Config.cpp.s
.PHONY : src/app/Config.s

# target to generate assembly for a file
src/app/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/Config.cpp.s
.PHONY : src/app/Config.cpp.s

src/app/main.o: src/app/main.cpp.o
.PHONY : src/app/main.o

# target to build an object file
src/app/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/main.cpp.o
.PHONY : src/app/main.cpp.o

src/app/main.i: src/app/main.cpp.i
.PHONY : src/app/main.i

# target to preprocess a source file
src/app/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/main.cpp.i
.PHONY : src/app/main.cpp.i

src/app/main.s: src/app/main.cpp.s
.PHONY : src/app/main.s

# target to generate assembly for a file
src/app/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/app/main.cpp.s
.PHONY : src/app/main.cpp.s

src/core/DerivedGates.o: src/core/DerivedGates.cpp.o
.PHONY : src/core/DerivedGates.o

# target to build an object file
src/core/DerivedGates.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/DerivedGates.cpp.o
.PHONY : src/core/DerivedGates.cpp.o

src/core/DerivedGates.i: src/core/DerivedGates.cpp.i
.PHONY : src/core/DerivedGates.i

# target to preprocess a source file
src/core/DerivedGates.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/DerivedGates.cpp.i
.PHONY : src/core/DerivedGates.cpp.i

src/core/DerivedGates.s: src/core/DerivedGates.cpp.s
.PHONY : src/core/DerivedGates.s

# target to generate assembly for a file
src/core/DerivedGates.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/DerivedGates.cpp.s
.PHONY : src/core/DerivedGates.cpp.s

src/core/GatePin.o: src/core/GatePin.cpp.o
.PHONY : src/core/GatePin.o

# target to build an object file
src/core/GatePin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/GatePin.cpp.o
.PHONY : src/core/GatePin.cpp.o

src/core/GatePin.i: src/core/GatePin.cpp.i
.PHONY : src/core/GatePin.i

# target to preprocess a source file
src/core/GatePin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/GatePin.cpp.i
.PHONY : src/core/GatePin.cpp.i

src/core/GatePin.s: src/core/GatePin.cpp.s
.PHONY : src/core/GatePin.s

# target to generate assembly for a file
src/core/GatePin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/GatePin.cpp.s
.PHONY : src/core/GatePin.cpp.s

src/core/InputSource.o: src/core/InputSource.cpp.o
.PHONY : src/core/InputSource.o

# target to build an object file
src/core/InputSource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/InputSource.cpp.o
.PHONY : src/core/InputSource.cpp.o

src/core/InputSource.i: src/core/InputSource.cpp.i
.PHONY : src/core/InputSource.i

# target to preprocess a source file
src/core/InputSource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/InputSource.cpp.i
.PHONY : src/core/InputSource.cpp.i

src/core/InputSource.s: src/core/InputSource.cpp.s
.PHONY : src/core/InputSource.s

# target to generate assembly for a file
src/core/InputSource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/InputSource.cpp.s
.PHONY : src/core/InputSource.cpp.s

src/core/LogicGate.o: src/core/LogicGate.cpp.o
.PHONY : src/core/LogicGate.o

# target to build an object file
src/core/LogicGate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/LogicGate.cpp.o
.PHONY : src/core/LogicGate.cpp.o

src/core/LogicGate.i: src/core/LogicGate.cpp.i
.PHONY : src/core/LogicGate.i

# target to preprocess a source file
src/core/LogicGate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/LogicGate.cpp.i
.PHONY : src/core/LogicGate.cpp.i

src/core/LogicGate.s: src/core/LogicGate.cpp.s
.PHONY : src/core/LogicGate.s

# target to generate assembly for a file
src/core/LogicGate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/LogicGate.cpp.s
.PHONY : src/core/LogicGate.cpp.s

src/core/OutputSink.o: src/core/OutputSink.cpp.o
.PHONY : src/core/OutputSink.o

# target to build an object file
src/core/OutputSink.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/OutputSink.cpp.o
.PHONY : src/core/OutputSink.cpp.o

src/core/OutputSink.i: src/core/OutputSink.cpp.i
.PHONY : src/core/OutputSink.i

# target to preprocess a source file
src/core/OutputSink.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/OutputSink.cpp.i
.PHONY : src/core/OutputSink.cpp.i

src/core/OutputSink.s: src/core/OutputSink.cpp.s
.PHONY : src/core/OutputSink.s

# target to generate assembly for a file
src/core/OutputSink.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/OutputSink.cpp.s
.PHONY : src/core/OutputSink.cpp.s

src/core/Wire.o: src/core/Wire.cpp.o
.PHONY : src/core/Wire.o

# target to build an object file
src/core/Wire.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/Wire.cpp.o
.PHONY : src/core/Wire.cpp.o

src/core/Wire.i: src/core/Wire.cpp.i
.PHONY : src/core/Wire.i

# target to preprocess a source file
src/core/Wire.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/Wire.cpp.i
.PHONY : src/core/Wire.cpp.i

src/core/Wire.s: src/core/Wire.cpp.s
.PHONY : src/core/Wire.s

# target to generate assembly for a file
src/core/Wire.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/core/Wire.cpp.s
.PHONY : src/core/Wire.cpp.s

src/simulation/CircuitSimulator.o: src/simulation/CircuitSimulator.cpp.o
.PHONY : src/simulation/CircuitSimulator.o

# target to build an object file
src/simulation/CircuitSimulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/simulation/CircuitSimulator.cpp.o
.PHONY : src/simulation/CircuitSimulator.cpp.o

src/simulation/CircuitSimulator.i: src/simulation/CircuitSimulator.cpp.i
.PHONY : src/simulation/CircuitSimulator.i

# target to preprocess a source file
src/simulation/CircuitSimulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/simulation/CircuitSimulator.cpp.i
.PHONY : src/simulation/CircuitSimulator.cpp.i

src/simulation/CircuitSimulator.s: src/simulation/CircuitSimulator.cpp.s
.PHONY : src/simulation/CircuitSimulator.s

# target to generate assembly for a file
src/simulation/CircuitSimulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/simulation/CircuitSimulator.cpp.s
.PHONY : src/simulation/CircuitSimulator.cpp.s

src/ui/GateRenderer.o: src/ui/GateRenderer.cpp.o
.PHONY : src/ui/GateRenderer.o

# target to build an object file
src/ui/GateRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/GateRenderer.cpp.o
.PHONY : src/ui/GateRenderer.cpp.o

src/ui/GateRenderer.i: src/ui/GateRenderer.cpp.i
.PHONY : src/ui/GateRenderer.i

# target to preprocess a source file
src/ui/GateRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/GateRenderer.cpp.i
.PHONY : src/ui/GateRenderer.cpp.i

src/ui/GateRenderer.s: src/ui/GateRenderer.cpp.s
.PHONY : src/ui/GateRenderer.s

# target to generate assembly for a file
src/ui/GateRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/GateRenderer.cpp.s
.PHONY : src/ui/GateRenderer.cpp.s

src/ui/InputHandler.o: src/ui/InputHandler.cpp.o
.PHONY : src/ui/InputHandler.o

# target to build an object file
src/ui/InputHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/InputHandler.cpp.o
.PHONY : src/ui/InputHandler.cpp.o

src/ui/InputHandler.i: src/ui/InputHandler.cpp.i
.PHONY : src/ui/InputHandler.i

# target to preprocess a source file
src/ui/InputHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/InputHandler.cpp.i
.PHONY : src/ui/InputHandler.cpp.i

src/ui/InputHandler.s: src/ui/InputHandler.cpp.s
.PHONY : src/ui/InputHandler.s

# target to generate assembly for a file
src/ui/InputHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/InputHandler.cpp.s
.PHONY : src/ui/InputHandler.cpp.s

src/ui/PaletteManager.o: src/ui/PaletteManager.cpp.o
.PHONY : src/ui/PaletteManager.o

# target to build an object file
src/ui/PaletteManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/PaletteManager.cpp.o
.PHONY : src/ui/PaletteManager.cpp.o

src/ui/PaletteManager.i: src/ui/PaletteManager.cpp.i
.PHONY : src/ui/PaletteManager.i

# target to preprocess a source file
src/ui/PaletteManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/PaletteManager.cpp.i
.PHONY : src/ui/PaletteManager.cpp.i

src/ui/PaletteManager.s: src/ui/PaletteManager.cpp.s
.PHONY : src/ui/PaletteManager.s

# target to generate assembly for a file
src/ui/PaletteManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/PaletteManager.cpp.s
.PHONY : src/ui/PaletteManager.cpp.s

src/ui/UIManager.o: src/ui/UIManager.cpp.o
.PHONY : src/ui/UIManager.o

# target to build an object file
src/ui/UIManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/UIManager.cpp.o
.PHONY : src/ui/UIManager.cpp.o

src/ui/UIManager.i: src/ui/UIManager.cpp.i
.PHONY : src/ui/UIManager.i

# target to preprocess a source file
src/ui/UIManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/UIManager.cpp.i
.PHONY : src/ui/UIManager.cpp.i

src/ui/UIManager.s: src/ui/UIManager.cpp.s
.PHONY : src/ui/UIManager.s

# target to generate assembly for a file
src/ui/UIManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/UIManager.cpp.s
.PHONY : src/ui/UIManager.cpp.s

src/ui/WireRenderer.o: src/ui/WireRenderer.cpp.o
.PHONY : src/ui/WireRenderer.o

# target to build an object file
src/ui/WireRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/WireRenderer.cpp.o
.PHONY : src/ui/WireRenderer.cpp.o

src/ui/WireRenderer.i: src/ui/WireRenderer.cpp.i
.PHONY : src/ui/WireRenderer.i

# target to preprocess a source file
src/ui/WireRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/WireRenderer.cpp.i
.PHONY : src/ui/WireRenderer.cpp.i

src/ui/WireRenderer.s: src/ui/WireRenderer.cpp.s
.PHONY : src/ui/WireRenderer.s

# target to generate assembly for a file
src/ui/WireRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/WireRenderer.cpp.s
.PHONY : src/ui/WireRenderer.cpp.s

src/ui/WireRouter.o: src/ui/WireRouter.cpp.o
.PHONY : src/ui/WireRouter.o

# target to build an object file
src/ui/WireRouter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/WireRouter.cpp.o
.PHONY : src/ui/WireRouter.cpp.o

src/ui/WireRouter.i: src/ui/WireRouter.cpp.i
.PHONY : src/ui/WireRouter.i

# target to preprocess a source file
src/ui/WireRouter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/WireRouter.cpp.i
.PHONY : src/ui/WireRouter.cpp.i

src/ui/WireRouter.s: src/ui/WireRouter.cpp.s
.PHONY : src/ui/WireRouter.s

# target to generate assembly for a file
src/ui/WireRouter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logic-gates-playground.dir/build.make CMakeFiles/logic-gates-playground.dir/src/ui/WireRouter.cpp.s
.PHONY : src/ui/WireRouter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... logic-gates-playground"
	@echo "... src/app/Application.o"
	@echo "... src/app/Application.i"
	@echo "... src/app/Application.s"
	@echo "... src/app/Config.o"
	@echo "... src/app/Config.i"
	@echo "... src/app/Config.s"
	@echo "... src/app/main.o"
	@echo "... src/app/main.i"
	@echo "... src/app/main.s"
	@echo "... src/core/DerivedGates.o"
	@echo "... src/core/DerivedGates.i"
	@echo "... src/core/DerivedGates.s"
	@echo "... src/core/GatePin.o"
	@echo "... src/core/GatePin.i"
	@echo "... src/core/GatePin.s"
	@echo "... src/core/InputSource.o"
	@echo "... src/core/InputSource.i"
	@echo "... src/core/InputSource.s"
	@echo "... src/core/LogicGate.o"
	@echo "... src/core/LogicGate.i"
	@echo "... src/core/LogicGate.s"
	@echo "... src/core/OutputSink.o"
	@echo "... src/core/OutputSink.i"
	@echo "... src/core/OutputSink.s"
	@echo "... src/core/Wire.o"
	@echo "... src/core/Wire.i"
	@echo "... src/core/Wire.s"
	@echo "... src/simulation/CircuitSimulator.o"
	@echo "... src/simulation/CircuitSimulator.i"
	@echo "... src/simulation/CircuitSimulator.s"
	@echo "... src/ui/GateRenderer.o"
	@echo "... src/ui/GateRenderer.i"
	@echo "... src/ui/GateRenderer.s"
	@echo "... src/ui/InputHandler.o"
	@echo "... src/ui/InputHandler.i"
	@echo "... src/ui/InputHandler.s"
	@echo "... src/ui/PaletteManager.o"
	@echo "... src/ui/PaletteManager.i"
	@echo "... src/ui/PaletteManager.s"
	@echo "... src/ui/UIManager.o"
	@echo "... src/ui/UIManager.i"
	@echo "... src/ui/UIManager.s"
	@echo "... src/ui/WireRenderer.o"
	@echo "... src/ui/WireRenderer.i"
	@echo "... src/ui/WireRenderer.s"
	@echo "... src/ui/WireRouter.o"
	@echo "... src/ui/WireRouter.i"
	@echo "... src/ui/WireRouter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

